# general
general {
    hide_cursor = true
    grace = 0
}

# animations
animation {
    animation = fade, 1, 5, linear
}

# background
background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3
    blur_size = 2
    noise = 0.015
    brightness = 0.92
    contrast = 1.4
    vibrancy = 1.3
    vibrancy_darkness = 0.1
}

# input
input-field {
    monitor =
    size = 300, 55
    outline_thickness = 4
    position = 0, -235
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(242, 243, 244, 0.80)
    inner_color = rgba(242, 243, 244, 0.80)
    font_family = Adwaita Sans
    font_color = rgb(121212)
    fade_on_empty = false
    placeholder_text = <span foreground="##121212" font-size="14pt">󰌾  Logged in as $USER</span>
    hide_input = false
    check_color = rgba(242, 243, 244, 0.50)
    fail_color = rgba(e64c4cee)
    fail_text = <span foreground="##e64c4cff" font-size="14pt">  $FAIL</span>
    halign = center
    valign = center
}

# date
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.83)
  font_size = 25
  font_family = Adwaita Sans
  position = 0, 120
  halign = center
  valign = center
}

# time
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%H:%M")"
  color = rgba(242, 243, 244, 0.83)
  font_size = 135
  font_family = Adwaita Sans Extrabold
  position = 0, -10
  halign = center
  valign = center
}
